//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourseWork
{
    using System;
    using System.Collections.Generic;
    
    public partial class free_seats
    {
        public int spectacle_id { get; set; }
        public string spectacle_name { get; set; }
        public int seat { get; set; }
        public int row { get; set; }
        public int hall_id { get; set; }
        public Nullable<int> num_ticket { get; set; }
        public int entry_id { get; set; }
    }
}
