//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourseWork
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TheatreEntities : DbContext
    {
        private static TheatreEntities _context;
        public TheatreEntities()
        : base("name=TheatreEntities")
        {
        }
        public static TheatreEntities GetContext()
        {
            if (_context == null)
                _context = new TheatreEntities();
            return _context;
        }
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<hall> hall { get; set; }
        public virtual DbSet<poster> poster { get; set; }
        public virtual DbSet<repertoire> repertoire { get; set; }
        public virtual DbSet<seat> seat { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<tickets> tickets { get; set; }
        public virtual DbSet<users> users { get; set; }
        public virtual DbSet<all_seats> all_seats { get; set; }
        public virtual DbSet<all_tikets> all_tikets { get; set; }
        public virtual DbSet<free_seats> free_seats { get; set; }
        public virtual DbSet<ticket_user> ticket_user { get; set; }
    }
}
